services:
  nginx:
    image: nginx:alpine
    container_name: frontend
    restart: always
    network_mode: host
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
      - ./dist:/usr/share/nginx/html