spring.application.name=zadinventory
# Configura��o do MySQL 8.0
spring.datasource.url=jdbc:mysql://192.168.100.23:3306/zadinventory?useSSL=false&serverTimezone=UTC
spring.datasource.username=banco
spring.datasource.password=senhabanco
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# Configura��es para resolver problemas de serializa��o
spring.jackson.serialization.fail-on-empty-beans=false
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.default-property-inclusion=non_null

# Otimiza��es de desempenho para carregamento de relacionamentos
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true

# Configura��o avan�ada de serializa��o
spring.jackson.serialization.write-single-elem-arrays-unwrapped=false
spring.jackson.deserialization.READ_UNKNOWN_ENUM_VALUES_USING_DEFAULT_VALUE=true

# Configura��es do JWT
jwt.secret=123456
jwt.expiration=86400000

#  Configura��o Hikari
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.keepalive-time=30000

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://192.168.1.15:8080/realms/zadinventory